version: '3.8'

services:
  ai_model:
    build: ./ai_model
    ports:
      - "8001:8001"
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - ai_model
    environment:
      - AI_MODEL_URL=http://ai_model:8001
